# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Posts
    url: '#posts'
    weight: 20
  - name: Talks
    url: '#talks'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: CV
    url: https://shiya-liu.github.io/CV/cv.html
    weight: 50
  - name: Portfolio
    identifier: portfolio
    weight: 60
  - name: Professional Philosophy
    parent: portfolio
    url: portfolio/philosophy
    weight: 10
  - name: Competence Assessment
    parent: portfolio
    url: portfolio/competence/
    weight: 20
  - name: Diversity Statements
    parent: portfolio
    url: portfolio/diversity
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 70
